modLoader = "javafml"
loaderVersion = "[38,)"
license = "Apache-2.0"

[[mods]]
modId = "iknowwhatimdoing"
version = "${file.jarVersion}"
displayName = "I Know What I'm Doing"
authors = "Chloe Dawn"
description = "Suppresses in-game tutorial hints"

[[dependencies.iknowwhatimdoing]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
side = "CLIENT"

[[dependencies.iknowwhatimdoing]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
side = "CLIENT"
