modLoader = "javafml"
loaderVersion = "[44.1,)"
license = "Apache-2.0"

[[mods]]
modId = "iknowwhatimdoing"
version = "${file.jarVersion}"
displayName = "I Know What I'm Doing"
authors = "Chloe Dawn"
description = "Suppresses in-game tutorial hints."

[[dependencies.iknowwhatimdoing]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
side = "CLIENT"

[[dependencies.iknowwhatimdoing]]
modId = "forge"
mandatory = true
versionRange = "[44.1,)"
side = "CLIENT"
